### ISSUE TITLE
Epic: Fix Patch Extractions

### ISSUE THREAD

**Issue by VincentVerelst** [WorldCereal/worldcereal-classification#241]
- [x] https://github.com/WorldCereal/worldcereal-classification/issues/231
- [x] https://github.com/WorldCereal/worldcereal-classification/issues/232
- [ ] https://github.com/WorldCereal/worldcereal-classification/issues/239
- [ ] https://github.com/WorldCereal/worldcereal-classification/issues/240
- [x] https://github.com/Open-EO/openeo-gfmap/issues/185
- [x] https://github.com/Open-EO/openeo-gfmap/issues/189

**Comment by kvantricht** [comment]
Some other things to consider:
- do we want to immediately also move the files to new output location based on UTM zone and S2 tile ID instead of h3 cell ID?
- do we want to re-compute matching S2 tile and update if needed in the netcdf file (and STAC metadata?)?
- ensure that interaction with STAC API works fine so we can have a good overview of what is finished, in error, still to be done etc
