### ISSUE TITLE
Epic: Fix Point Extractions

### ISSUE THREAD

**Issue by VincentVerelst** [WorldCereal/worldcereal-classification#242]
- [x] https://github.com/Open-EO/openeo-gfmap/issues/189
- [x] Test `aggregate_spatial` now works for FeatureCollections containing only a single point
- [x] https://github.com/Open-EO/openeo-gfmap/issues/187
- [x] Increase default Python memory settings
- [x] Update output path generator

**Comment by VincentVerelst** [comment]
@kvantricht, the necessary changes for point extractions are now available on the GFMap main branch. What's left to be done is increase Python memory and update the output_path_generator for point extractions. I understand you are already working on this in a feature branch in this repository. 

Should any other issues come up for point extractions, you can add them to this Epic. If not, we can close it.
